import React, { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../../styles/Home.module.css';

function IndexPage() {
  const router = useRouter();

  useEffect(() => {
    router.push('/dashboard');
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>HYVE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="https://cdn.rawgit.com/mfd/f3d96ec7f0e8f034cc22ea73b3797b59/raw/856f1dbb8d807aabceb80b6d4f94b464df461b3e/gotham.css" />
        <link href="/cf-gotham-fonts/gotham-font.css" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export default IndexPage;
